spring:
  application:
    name: springcloud-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wl1990/springcloud.git
          searchPaths: spring-cloud
          username: 
          password: 
      label: respo
  rabbitmq:
    host: localhost
    port: 5672
    username: wanglei
    password: beijing1990
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
management:
  security:
    enabled: false  